# Site settings
title: Erik Ramsey
description: 'Computer Science Undergrad at University of Nevada Las Vegas'
url: 'http://erikrramsey.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Erik Ramsey'
  email: erikr.ramsey@gmail.com
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
  github_username:  erikrramsey
  linkedin_username:  erikr-ramsey

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
